# Generated by Django 5.1.4 on 2025-01-20 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_main_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Main_Img',
        ),
    ]
