# Generated by Django 5.1.4 on 2025-01-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Main_Img',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
