# Generated by Django 5.1.4 on 2025-01-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color_rotation',
            field=models.IntegerField(default=0),
        ),
    ]
