# Generated by Django 5.1.4 on 2025-01-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_color_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brief_description',
            field=models.TextField(default='Unbeschreiblich.', max_length=1000),
        ),
    ]
