# Generated by Django 5.1.4 on 2025-01-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_main_img_post_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='by_me',
            field=models.BooleanField(default=False),
        ),
    ]
