# Generated by Django 5.1.4 on 2025-02-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_content_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authors_comment',
            field=models.TextField(blank=True),
        ),
    ]
