# Generated by Django 5.1.4 on 2025-10-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comic'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='thumbnail_img',
            field=models.ImageField(default=None, upload_to='comics/'),
        ),
    ]
