# Generated by Django 5.1.4 on 2025-10-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_comic_thumbnail_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='thumbnail_img',
        ),
    ]
