# Generated by Django 5.1.4 on 2025-10-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_comic_thumbnail_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='thumbnail_img',
            field=models.ImageField(default='images/default.png', upload_to='comics/'),
        ),
    ]
