# Generated by Django 5.1.4 on 2025-10-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_comic_thumbnail_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='thumbnail_img',
            field=models.ImageField(blank=True, null=True, upload_to='comics/'),
        ),
    ]
